### ISSUE TITLE
RSS feed links broken

### ISSUE THREAD

**Issue by rtpax** [RyanBrewer317/ryanbrewer-dev#3]
The rss feed is still using .html, but the website no longer uses the extension for urls. For example the link for the most recent post goes to "https://ryanbrewer.dev/posts/cricket.html", which results in a 404. The feed could either be updated to use the format "https://ryanbrewer.dev/posts/cricket", or else the website could redirect .html sites to the new urls. (Personally would prefer the second solution, as some rss readers cache old posts and will not update to the new links.)

**Comment by RyanBrewer317** [comment]
Thank you so much for catching that! I just pushed a fix that more or less does both of those. The old links should all redirect correctly now, and the feed will generate correct links from now on. 

This did mean updating the old links in the feed, because the feed is completely auto-generated from the posts. But I separately added redirects for those pages, in the event of caching (and to keep all my old backlinks alive on reddit and whatnot)
